### ISSUE TITLE
Tests and bitrot

### ISSUE THREAD

**Issue by voila** [glennsl/bucklescript-cookbook#4]
The Bucklescript and the buckletypes libraries are still changing. What should we do to manage code that is likely to break in the future ? 
- Should we mention the version of BS we are using?
- There is no tags (for say, a specific version of bs-json) we can reference in the examples. Should we have some tests for this repo, so users can quickly see what examples work with their setup ?

**Comment by glennsl** [comment]
I've been working on a tool to help with this: https://github.com/glennsl/md-codecheck

`package.json` should then be the authoritative source for which versions to use, and should preferably just be the latest published version of each.

**Comment by voila** [comment]
This look exactly like the ticket!
